export const SET_ON_TOP = "SET_ON_TOP";
export const SET_NOTIFY = "SET_NOTIFY";
export const SET_DARKMODE = "SET_DARKMODE";
export const SHOW_SETTING = "SHOW_SETTING";
export const SET_FULL_SCREEN_ON_BREAK = "SET_FULL_SCREEN_ON_BREAK";
export const SET_UPDATING = "SET_UPDATING";
export const SET_DOWNLOAD_COMPLETED = "SET_DOWNLOAD_COMPLETED";
