name: productivity-timer
version: git
summary: Beautiful Time Management App for Productivity inspired by Pomodoro Technique.
description: |
  This application is Free and OpenSource and has a lot of useful features that helps boost your productivity. It uses the method called Pomodoro Technique which is proven and tested to increase your overall productiveness.

grade: stable
confinement: strict

apps:
  productivity-timer:
    command: $SNAP/bin/productivity-timer
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  productivity-timer:
    source: .
    plugin: nodejs

    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6

    after:
      - desktop-gtk2
