export const SET_WORK_TIME = "SET_WORK_TIME";
export const SET_SHORT_BREAK = "SET_SHORT_BREAK";
export const SET_LONG_BREAK = "SET_LONG_BREAK";
export const SET_SESSION_ROUNDS = "SET_SESSION_ROUNDS";
export const RESTORE_DEFAULT = "RESTORE_DEFAULT";
