declare module "*.woff";
declare module "*.woff2";
declare module "*.png";
declare module "*.jpg";
declare module "*.wav";
declare module "*.mp3";
declare module "*.mp4";
declare module "*.ogv";
declare module "*.webm";
