name: "Pre-commit consistency check"

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}-precommit
  cancel-in-progress: true

jobs:
  pre-commit-check:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            addedOrModified:
              - added|modified: '**'

      # run only if changed files were detected
      - name: Run against changes
        uses: pre-commit/action@v3.0.1
        if: steps.filter.outputs.addedOrModified == 'true'
        with:
          extra_args: --files ${{ steps.filter.outputs.addedOrModified_files }}

      # run if no changed files were detected (e.g. workflow_dispatch on master branch)
      - name: Run against all files
        uses: pre-commit/action@v3.0.1
        if: steps.filter.outputs.addedOrModified != 'true'
        with:
          extra_args: --all-files
